github:
  is_project_page: false

theme: jekyll-theme-Cayman
markdown: GFM
title: Machine Vision Innovation (MVI) Tournament
description: IEEE International Conference on Image Processing 2024 (ICIP-2024)
